name: 'RN bundler and uploader'
description: 'Bundles and uploads your code'
inputs:
  dist_path:
    description: 'output path for the build package'
    required: true
    default: 'dist'
  app_name:
    description: 'Name of the application'
    required: true
  storage_bucket:
    description: 'Name of the GCS or S3 bucket'
    require: true
  storage_type:
    description: 'gcs or s3'
    required: true
    default: 'gcs'
  pr_number:
    description: 'The number of the pull request'
    required: true
  github_token:
    description: 'Token required to use octokit'
    default: ${{ github.token }}
outputs:
  deep-url:
    description: 'Deep url that mobile clients can use to tophat'
runs:
  using: 'node12'
  main: 'index.js'